package com.example.paygambarlartarixi.util

import com.example.paygambarlartarixi.R
import com.example.paygambarlartarixi.database.Image

object ObjectList {
    var tarixList = mutableListOf(
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.islam,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        Image(
            "foto",
            R.drawable.person,
        ),
        )
}
